- name: installtion and configuraiton of nginx
  hosts: all
  tasks:
    - name: installtion of nginx
      yum:
         name: nginx
         state: present
    - name: starting of nginx service
      service:
          name: nginx
          state: started

